apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-global-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.mysql.password }}
  INFLUX_TOKEN: {{ .Values.global.influx.token }}
