apiVersion: v2
name: infra-chart
description: Energy Tracker Infrastructure Components
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: "0.1.0"
    condition: mysql.enabled
  - name: kafka
    version: "0.1.0"
    condition: kafka.enabled
  - name: influxdb
    version: "0.1.0"
    condition: influxdb.enabled
  - name: mailpit
    version: "0.1.0"
    condition: mailpit.enabled
  - name: kafka-ui
    version: "0.1.0"
    condition: kafkaUi.enabled
    alias: kafkaUi
  - name: ollama
    version: "0.1.0"
    condition: ollama.enabled
