apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailpit
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.smtpPort }}
    targetPort: 1025
    protocol: TCP
    name: smtp
  - port: {{ .Values.service.webPort }}
    targetPort: 8025
    protocol: TCP
    name: web
    {{- if .Values.service.webNodePort }}
    nodePort: {{ .Values.service.webNodePort }}
    {{- end }}
  selector:
    app: mailpit
