ingress:
  enabled: false

global:
  namespace: default

  # MySQL connection details test
  mysql:
    host: infra-mysql  # ie the name of the release must be "infra"
    port: 3306
    database: energy_tracker
    username: root
    password: password

# User Service Configuration
userService:
  enabled: true
  image:
    repository: public.ecr.aws/v6r1m8q2/energy-tracker/user-service
    tag: latest
    pullPolicy: Always
  port: 8080
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Future services can be added here:
deviceService:
  enabled: true
  image:
    repository: public.ecr.aws/v6r1m8q2/energy-tracker/device-service
    tag: latest
    pullPolicy: Always
  port: 8081
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
ingestionService:
  enabled: true
  image:
    repository: public.ecr.aws/v6r1m8q2/energy-tracker/ingestion-service
    tag: latest
    pullPolicy: Always
  port: 8082
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Disabled until deployed â€” port stubs needed for ingress template
usageService:
  enabled: false
  port: 8083

alertService:
  enabled: false
  port: 8084

insightService:
  enabled: false
  port: 8085
